function createfigure(xdata1, ydata1, zdata1, cdata1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1,CDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 29-Sep-2012 18:47:36

% Create figure
figure1 = figure('XVisual','');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'YMinorGrid','on',...
    'FontSize',12,...
    'CLim',[-300 -60]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.011609977324263 5.00390022675737]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 5000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-403.785503265024 -94.440052594252]);
view(axes1,[108 34]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(xdata1,ydata1,zdata1,cdata1,'Parent',axes1,'EdgeColor','none');

% Create xlabel
xlabel('Time [s]');

% Create ylabel
ylabel('Frequency [Hz]');

% Create title
title('ReSynth Final Audio');

% Create colorbar
colorbar('peer',axes1,'FontSize',12);

